// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjydgoiiyyaofeuqtbrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqeWRnb2lpeXlhb2ZldXF0YnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MjI3MjcsImV4cCI6MjA1MjA5ODcyN30.QYqTE-7ZStqlhyzdPCVl2TWsqAAHdH2VVH9nAn4yurI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);